// Bookmarks data in JavaScript format for local file compatibility
// This file is automatically generated from bookmarks.json
// Edit bookmarks.json and regenerate this file to update bookmarks

window.bookmarkApp.loadBookmarksData({
    "settings":  {
                     "helpSystem":  {
                                        "sections":  [
                                                         {
                                                             "title":  "📋 Overview",
                                                             "id":  "overview",
                                                             "content":  {
                                                                             "tips":  [
                                                                                          {
                                                                                              "icon":  "💡",
                                                                                              "text":  "Click on any ❓ icon throughout the interface for context-specific help."
                                                                                          }
                                                                                      ],
                                                                             "features":  [
                                                                                              {
                                                                                                  "description":  "Organise bookmarks into logical groups (M365 Sites, Admin Tools, LOB Sites, etc.)",
                                                                                                  "title":  "Categories"
                                                                                              },
                                                                                              {
                                                                                                  "description":  "Quickly find bookmarks by name, description, or tags",
                                                                                                  "title":  "Search"
                                                                                              },
                                                                                              {
                                                                                                  "description":  "Filter bookmarks using multiple tags",
                                                                                                  "title":  "Tags"
                                                                                              },
                                                                                              {
                                                                                                  "description":  "Choose from professional color schemes",
                                                                                                  "title":  "Themes"
                                                                                              },
                                                                                              {
                                                                                                  "description":  "Backup your data or sync with browsers",
                                                                                                  "title":  "Import/Export"
                                                                                              }
                                                                                          ],
                                                                             "description":  "BookMark Manager is a professional bookmark organisation system designed for corporate and business use."
                                                                         }
                                                         }
                                                     ]
                                    },
                     "defaultTheme":  "admin-dark",
                     "version":  "2.2.0",
                     "helpDesk":  {
                                      "defaultEmail":  "propakit@cpcfoods.co.uk",
                                      "emailBodyTemplate":  "Hello IT Support,\n\nI need assistance with the following service:\n\nService: {serviceName}\nURL: {serviceUrl}\nDescription: {serviceDescription}\n\nIssue Description:\n[Please describe your issue here]\n\nSystem Information:\n- Browser: {browserInfo}\n- Hostname: {hostname}\n- Date/Time: {timestamp}\n- User: {userName}\n\nAdditional Information:\n[Any other relevant details]\n\nThank you for your assistance.\n\nBest regards,\n{userName}",
                                      "emailSubjectTemplate":  "Help Request: {serviceName}"
                                  }
                 },
    "categories":  [
                       {
                           "bookmarks":  [
                                             {
                                                 "url":  "https://support.microsoft.com/en-GB/microsoft-365",
                                                 "logo":  "",
                                                 "name":  "Microsoft 365 Support",
                                                 "supportType":  "none",
                                                 "helpInfo":  {
                                                                  "contactMethod":  {
                                                                                        "type":  "self-service",
                                                                                        "message":  "This is Microsoft\u0027s official support portal for Microsoft 365 services and applications."
                                                                                    },
                                                                  "purpose":  "Get help and support for Microsoft 365 applications and services",
                                                                  "accessProcess":  "self-service",
                                                                  "accessLevel":  "Public",
                                                                  "restrictions":  "No restrictions - publicly available",
                                                                  "estimatedTime":  "Immediate access",
                                                                  "description":  "Official Microsoft support portal providing help articles, troubleshooting guides, and community support for Microsoft 365 applications and services."
                                                              },
                                                 "tags":  [
                                                              "microsoft",
                                                              "support",
                                                              "help",
                                                              "office365"
                                                          ],
                                                 "description":  "Official Microsoft support for Microsoft 365 applications and services"
                                             },
                                             {
                                                 "url":  "https://support.microsoft.com/en-gb/outlook",
                                                 "logo":  "",
                                                 "name":  "Outlook Support",
                                                 "supportType":  "none",
                                                 "helpInfo":  {
                                                                  "contactMethod":  {
                                                                                        "type":  "self-service",
                                                                                        "message":  "Microsoft\u0027s official support portal for Outlook email client and related services."
                                                                                    },
                                                                  "purpose":  "Get help with Outlook email, calendar, and contact management",
                                                                  "accessProcess":  "self-service",
                                                                  "accessLevel":  "Public",
                                                                  "restrictions":  "No restrictions - publicly available",
                                                                  "estimatedTime":  "Immediate access",
                                                                  "description":  "Official Microsoft support portal for Outlook, providing help with email setup, troubleshooting, calendar management, and advanced features."
                                                              },
                                                 "tags":  [
                                                              "outlook",
                                                              "email",
                                                              "calendar",
                                                              "microsoft"
                                                          ],
                                                 "description":  "Official Microsoft support for Outlook email and calendar"
                                             },
                                             {
                                                 "url":  "https://support.microsoft.com/en-gb/word",
                                                 "logo":  "",
                                                 "name":  "Word Support",
                                                 "supportType":  "none",
                                                 "helpInfo":  {
                                                                  "contactMethod":  {
                                                                                        "type":  "self-service",
                                                                                        "message":  "Microsoft\u0027s official support portal for Microsoft Word document processing."
                                                                                    },
                                                                  "purpose":  "Get help with Microsoft Word document creation, editing, and formatting",
                                                                  "accessProcess":  "self-service",
                                                                  "accessLevel":  "Public",
                                                                  "restrictions":  "No restrictions - publicly available",
                                                                  "estimatedTime":  "Immediate access",
                                                                  "description":  "Official Microsoft support portal for Word, covering document creation, formatting, collaboration features, and troubleshooting common issues."
                                                              },
                                                 "tags":  [
                                                              "word",
                                                              "documents",
                                                              "formatting",
                                                              "microsoft"
                                                          ],
                                                 "description":  "Official Microsoft support for Word document processing"
                                             },
                                             {
                                                 "url":  "https://support.microsoft.com/en-gb/excel",
                                                 "logo":  "",
                                                 "name":  "Excel Support",
                                                 "supportType":  "none",
                                                 "helpInfo":  {
                                                                  "contactMethod":  {
                                                                                        "type":  "self-service",
                                                                                        "message":  "Microsoft\u0027s official support portal for Microsoft Excel spreadsheet application."
                                                                                    },
                                                                  "purpose":  "Get help with Excel spreadsheets, formulas, charts, and data analysis",
                                                                  "accessProcess":  "self-service",
                                                                  "accessLevel":  "Public",
                                                                  "restrictions":  "No restrictions - publicly available",
                                                                  "estimatedTime":  "Immediate access",
                                                                  "description":  "Official Microsoft support portal for Excel, providing guidance on formulas, pivot tables, charts, data analysis, and advanced Excel features."
                                                              },
                                                 "tags":  [
                                                              "excel",
                                                              "spreadsheets",
                                                              "formulas",
                                                              "microsoft"
                                                          ],
                                                 "description":  "Official Microsoft support for Excel spreadsheets and data analysis"
                                             },
                                             {
                                                 "url":  "https://support.microsoft.com/en-gb/powerpoint",
                                                 "logo":  "",
                                                 "name":  "PowerPoint Support",
                                                 "supportType":  "none",
                                                 "helpInfo":  {
                                                                  "contactMethod":  {
                                                                                        "type":  "self-service",
                                                                                        "message":  "Microsoft\u0027s official support portal for Microsoft PowerPoint presentation software."
                                                                                    },
                                                                  "purpose":  "Get help with PowerPoint presentations, animations, and design features",
                                                                  "accessProcess":  "self-service",
                                                                  "accessLevel":  "Public",
                                                                  "restrictions":  "No restrictions - publicly available",
                                                                  "estimatedTime":  "Immediate access",
                                                                  "description":  "Official Microsoft support portal for PowerPoint, covering slide creation, animations, transitions, design templates, and presentation best practices."
                                                              },
                                                 "tags":  [
                                                              "powerpoint",
                                                              "presentations",
                                                              "slides",
                                                              "microsoft"
                                                          ],
                                                 "description":  "Official Microsoft support for PowerPoint presentations"
                                             },
                                             {
                                                 "url":  "https://support.microsoft.com/en-gb/onedrive",
                                                 "logo":  "",
                                                 "name":  "OneDrive Support",
                                                 "supportType":  "none",
                                                 "helpInfo":  {
                                                                  "contactMethod":  {
                                                                                        "type":  "self-service",
                                                                                        "message":  "Microsoft\u0027s official support portal for OneDrive cloud storage service."
                                                                                    },
                                                                  "purpose":  "Get help with OneDrive file storage, sharing, and synchronization",
                                                                  "accessProcess":  "self-service",
                                                                  "accessLevel":  "Public",
                                                                  "restrictions":  "No restrictions - publicly available",
                                                                  "estimatedTime":  "Immediate access",
                                                                  "description":  "Official Microsoft support portal for OneDrive, providing help with file storage, sharing, synchronization, and troubleshooting sync issues."
                                                              },
                                                 "tags":  [
                                                              "onedrive",
                                                              "cloud",
                                                              "storage",
                                                              "microsoft"
                                                          ],
                                                 "description":  "Official Microsoft support for OneDrive cloud storage"
                                             }
                                         ],
                           "name":  "Microsoft Tools Help",
                           "id":  "microsoft-help",
                           "color":  "#0078d4",
                           "description":  "Online help and support for Microsoft applications",
                           "collapsed":  true
                       },
                       {
                           "bookmarks":  [
                                             {
                                                 "url":  "https://notion.so",
                                                 "logo":  "",
                                                 "name":  "Notion",
                                                 "supportType":  "popup",
                                                 "tags":  [
                                                              "docs",
                                                              "wikis",
                                                              "databases"
                                                          ],
                                                 "description":  "All-in-one workspace"
                                             }
                                         ],
                           "name":  "Productivity",
                           "id":  "productivity",
                           "color":  "#00b294",
                           "description":  "Personal workflow tools"
                       }
                   ]
});
